### ISSUE TITLE
script

### ISSUE THREAD

**Issue by songdun** [Array-Huang/webpack-seed-v2#2]
这个版本没有npm run dll	npm run analyse 这俩个命令了？

**Comment by Array-Huang** [comment]
`npm run dll`是有的，放到core目录的[package.json](https://github.com/Array-Huang/webpack-seed-v2/blob/master/core/package.json)里了

至于`npm run analyse`，哈哈哈，还真是没有放进来，不过放进来也不是什么难事，你要不要自己尝试一下呢？

**Comment by songdun** [comment]
!~! 我用这个来搭建基于react的spa是不是有点坑自己呢？

**Comment by Array-Huang** [comment]
其实都可以的，换我来改造的话不是什么事儿。spa也就是单入口，多入口都能搞定了，单入口自然不在话下；另一方面就是整合进React。

所以关键是，你有没有搞透我这套脚手架各方面的内容，如果你都搞明白了，随便改造甚至说自己从头搭一套都不是什么难事。

如果任务急，你其实是可以找一套现成的React脚手架（Github上很多吧，找个star多的呗我也没有能推荐的），项目马上就能开工，但请记得，这脚手架（无论是哪一个脚手架）其中的内容，你始终是得花时间搞透的。
