### ISSUE TITLE
dev script

### ISSUE THREAD

**Issue by songdun** [Array-Huang/webpack-seed-v2#3]
`npm run build	根据webpack.config.js，build出一份生产环境的代码
npm run dev	根据webpack.dev.config.js，build出一份开发环境的代码
npm run watch	在npm run dev的基础上添加-- watch，实时监控源文件，建议开发时使用这项
npm run start	开启webpack-dev-server，然后就可以在 http://localhost:8080/ 查看成品了
npm run profile	显示编译过程中每一项资源的耗时，用来调优的`

开发模式不是应该用start会更好吗？build打包的命令中为什么不是用-p呢？

**Comment by Array-Huang** [comment]
在webpack-dev-server下，我无论如何都搞不定热更新，所以理论上需要同时开着`npm run watch`和`npm run start`。

另外，`-p`是
> Equals to --optimize-minimize --optimize-occurrence-order
我这边没啥需求呢，你要用的话可以加上呗

**Comment by songdun** [comment]
npm start  后面写了个--content-base build 用了这个的话 是要基于 build这个文件夹 这个和webpack-dev-server的用法不一样吧 ，如果没有run build的话 start是跑起来是找不到文件的

**Comment by Array-Huang** [comment]
嗯，实际上我自己开发的时候并不用webpack-dev-server，我是用apache的，所以`npm run start`只能说是预览。

**Comment by songdun** [comment]
部署的时候不应该是直接把build文件夹里的文件全部放到nginx上吗？

**Comment by Array-Huang** [comment]
对的，所以`--content-base build`就是以build目录为根目录

**Comment by songdun** [comment]
为什么我启动你这个项目的时候webpack-dev-server没有启动一个websocket呢？我其他的项目用webpack-dev-server的时候都会有一个websocket，我想这个才是这个项目不能热更新的问题吧

**Comment by Array-Huang** [comment]
我现在没有开 `--hot`

**Comment by songdun** [comment]
我加了--hot 他也没有websoket啊

**Comment by Array-Huang** [comment]
有大兄弟似乎研究出来了：

[《关于前端工程化的思考及《webpack多页应用架构系列》mock开发环境改造》](http://nutlee.space/2016/10/24/%E5%85%B3%E4%BA%8E%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%8C%96%E7%9A%84%E6%80%9D%E8%80%83%E5%8F%8A%E3%80%8Awebpack%E5%A4%9A%E9%A1%B5%E5%BA%94%E7%94%A8%E6%9E%B6%E6%9E%84%E7%B3%BB%E5%88%97%E3%80%8Bmock%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E6%94%B9%E9%80%A0/)
[Nutlee/webpack-seed](https://github.com/Nutlee/webpack-seed)

**Comment by songdun** [comment]
我已经成功的参照他的方法把你这个项目的热部署弄好了，但是不能按照他的用supervisor来启动，否则一旦有更改，supervisor会把websocket停掉再重启，这样就失去了webpack-dev-server热部署的意义了，直接用node启动就好了。
