### ISSUE TITLE
添加新的模块

### ISSUE THREAD

**Issue by songdun** [Array-Huang/webpack-seed-v2#5]
---base/dir-vars.config.js 文件
`**/**//**/mE.srcDir = path.resolve(mE.srcRootDir, './src');** `

---alias.config.js 文件
module.exports = {
  // 模块别名的配置，为了使用方便，一般来说所有模块都是要配置一下别名的
  /* 各种目录 */

`  **src: path.resolve(dirVars.srcDir, '/index'),**`
  
};

我想添加一个src文件夹作为react组件目录，在这以上两个文件里添加了代码，但是在index/index/page.js文件里用`**require('src')**`;的时候报错了，这个有什么要改的吗？

**Comment by Array-Huang** [comment]
这个index是什么后缀名的？是js的么？如果不是的话你补齐看看？

**Comment by songdun** [comment]
是.js 补齐了也不行 是只需要修改项目下的 还是连core文件夹里的也要修改呢？

**Comment by Array-Huang** [comment]
不需要改core目录的。

应该还是路径的问题吧，看你上面的配置，这个index.js应该是在项目目录（以我原来的示范例子那就是*admin-example-1*目录）下的*src*目录里，你确定一下路径是不是对的？

**Comment by Array-Huang** [comment]
如果实在不行你就打包发我邮箱吧：hyw125@yeah.net

**Comment by songdun** [comment]
找到原因了 是因为eslint报错了 所以模块没有被构建
