### ISSUE TITLE
引入react报错

### ISSUE THREAD

**Issue by songdun** [Array-Huang/webpack-seed-v2#6]
`ERROR in ./pages/index/index/page.js
Module build failed: SyntaxError: E:/webpack-seed-v2/example-admin-2-single-page/pages/index/index/page.js: Unexpected token (6:1)

    4 | const config = require("configModule");
    5 | const RootClass = (
    6 |   <div>
       |   ^
    7 |           123
    8 |   </div>
    9 |   );`
引入react就报错，这个是什么问题啊 
index/index/page.js  文件里的代码如下

require("cp");
import React from "react";
// require('src');
const config = require("configModule");
const RootClass = (
	```
<div>
		123
	</div>
```
	);
// console.log(config)
$(() => {
  /* global IS_PRODUCTION:true */ // 由于ESLint会检测没有定义的变量，因此需要这一个`global`注释声明IS_PRODUCTION是一个全局变量(当然在本例中并不是)来规避warning
	if (!IS_PRODUCTION) {
		console.log("如果你看到这个Log，那么这个版本实际上是开发用的版本");
		console.log(config.API_ROOT);
		console.info(RootClass);
	}
});

**Comment by Array-Huang** [comment]
你那不是jsx吗？怎么写到js里面来了

**Comment by songdun** [comment]
写react不就是这样写吗？

**Comment by Array-Huang** [comment]
jsx要用jsx-loader

**Comment by songdun** [comment]
{
      test: /\.jsx?$/,
      loader: 'babel-loader',
      exclude: /(node_modules|bower_components)/,
      extensions: ['.jsx', '.js'],
      query: {
        presets: ['es2015', 'react']
      }
    },

我是这么配的啊 babel可以转化react啊

**Comment by Array-Huang** [comment]
那我就不太清楚了，我不用react的

**Comment by xiaomeimeimei** [comment]
我想问 大神  要用到的每一张图片  都要写到build-file.config.js 里吗？

**Comment by Array-Huang** [comment]
实际上并不是，你是可以直接在模板里直接require图片的
