### ISSUE TITLE
配置有误，不能执行，webpack-seed 没问题。

### ISSUE THREAD

**Issue by doocal** [Array-Huang/webpack-seed-v2#8]
如图：
![qq 20170316142158](https://cloud.githubusercontent.com/assets/2017549/23984355/17cd298c-0a54-11e7-95af-d128d94e60b2.png)

**Comment by Array-Huang** [comment]
不是配置有误，是因为这个仓库还是webpack1版本的，你用了webpack2来执行了

**Comment by Array-Huang** [comment]
好吧，这事其实也怪我，npm上默认install的已经是webpack2了，我找个时间改改吧
